[package]
name = "voli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A fast, no-admin package manager for Windows"

[[bin]]
name = "voli"
path = "src/main.rs"

[dependencies]
voli-core = { workspace = true }
stela = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }
indicatif = { workspace = true }
ureq = { workspace = true }
tempfile = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
voli-core = { workspace = true }
tempfile = { workspace = true }
zip = { workspace = true }
sha2 = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(windows)'.build-dependencies]
winresource = { workspace = true }
image = { workspace = true }
ico = { workspace = true }
