[package]
name = "voli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A fast, no-admin package manager for Windows"

[[bin]]
name = "voli"
path = "src/main.rs"

[dependencies]
voli-core = { workspace = true }
clap = { workspace = true }
